version: "3.8"

services:
  db:
    image: mysql:8
    container_name: crawler-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crawlerdb
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawlerpass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
