name: Deploy App to AWS

on:
  push:
    branches:
      - main # trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ec2-user
      FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET }}

    steps:
      # ---------------------------
      # 1. Checkout Repository
      # ---------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------------------------
      # 2. Setup Node.js for React
      # ---------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # ---------------------------
      # 3. Build React Frontend
      # ---------------------------
      - name: Install and build frontend
        working-directory: crawler-frontend
        run: |
          npm ci
          npm run build

      # ---------------------------
      # 4. Deploy to S3
      # ---------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync frontend to S3
        run: |
          aws s3 sync frontend/dist s3://$FRONTEND_BUCKET --delete

      # ---------------------------
      # 5. Deploy Backend to EC2
      # ---------------------------
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy backend via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/app || git clone https://github.com/<your-repo>.git app && cd app
            git pull origin main
            docker compose down || true
            docker compose up -d --build
          EOF
